language: node_js
node_js:
  - 14
dist: trusty
services: 
  - docker

before_install:
  - docker build -t bk007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bk007/docker-react npm run test